/*****************************************************************************
Copyright (c) netsecsp 2012-2032, All rights reserved.

Developer: Shengqian Yang, from China, E-mail: netsecsp@hotmail.com, last updated 07/05/2016
http://asynframe.sf.net

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

* Redistributions of source code must retain the above
copyright notice, this list of conditions and the
following disclaimer.

* Redistributions in binary form must reproduce the
above copyright notice, this list of conditions
and the following disclaimer in the documentation
and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*****************************************************************************/
import "IAsynNetwork.idl";

    cpp_quote("#pragma pack(push, 1)")

    /////////////////////////////////////////////////////////////////////////////
    [// 显式继承IKeyvalSetter
        object,
        uuid(7A81B83C-2FF2-4bda-A5A6-336AC940F12E),
        helpstring("INetmsg Interface"),
        pointer_default(unique)
    ]
    interface INetmsg : IKeyvalSetter
    {
        HRESULT Getline( [out]STRING* Method, [out]STRING* Param1, [out]STRING* Param2 );
        HRESULT Setline( [in ]STRING  Method, [in ]STRING  Param1, [in ]STRING  Param2 );
    };

    /////////////////////////////////////////////////////////////////////////////
    [// 提供消息/数据分离的接口
        object,
        uuid(DCA84EA9-CC7F-4d6a-B7E5-7FD443F83BC1),
        helpstring("INet Interface"),
        pointer_default(unique)
    ]
    interface INet : IAsynRawSocket
    {
        HRESULT SendPacket( [in ]STRING Method, [in ]STRING Param1, [in ]IUnknown *Param2, [in ]IAsynIoOperation* pAsynIoOperation );
    };
    
    /////////////////////////////////////////////////////////////////////////////
    [// 提供Http数据传输隧道的接口
        object,
        uuid(DFFEA42D-B431-4C7B-876C-D545A4A58EC9),
        helpstring("IHttpTxTunnel Interface"),
        pointer_default(unique)
    ]
    interface IHttpTxTunnel : IUnknown
    {
        HRESULT SetEnabled( [in ]uint32_t method ); //method=0表示只处理协议 method=1表示数据透传
    };

    cpp_quote("#pragma pack(pop)")
